version: '3.8'
services:
  aiware-db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: aiware
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aiware
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    